# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Akash Paul
tagline:          'CZZ'
description:      'My projects journal'
url:              http://iakashpaul.github.io
baseurl:          /

author:
  name:           'Akash Paul'
  url:            https://twitter.com/iAkashPaul

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/iakashpaul
