# Dependencies
markdown:     kramdown
highlighter:  rouge  

# Permalinks
permalink:        pretty


# Setup
title:            Akash Paul
tagline:          'CZZ'
description:      'My Jekyll logbook'
url:              https://iakashpaul.github.io
baseurl:          /

author:
  name:           'Akash Paul'
  url:            https://twitter.com/iakashpaul

paginate:         10
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/iakashpaul
